function createSensitivityBarGraph(ymatrix1, varargin)
%CREATEFIGURE(ymatrix1)
%  YMATRIX1:  bar matrix data

%  Auto-generated by MATLAB on 12-Mar-2023 19:14:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0882040382571732 0.153846153846154 0.883103081827843 0.771153846153846]);
hold(axes1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(ymatrix1,'Parent',axes1);
for i = 1:length(varargin)
    set(bar1(i),'DisplayName',varargin{i});
end

% Create ylabel
ylabel('Change in Energy (%)','FontName','Times');

% Create xlabel
xlabel('Change in Parameter (%)','FontName','Times');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times','FontSize',24,'XTick',[1 2 3 4 5 6 7 8 9],...
    'XTickLabel',{'-20','-15','-10','-5','0','5','10','15','20'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','south');

