function createEffeciencyMap(cdata1)
%CREATEFIGURE(cdata1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 25-Feb-2023 10:36:45

% Create figure
figure1 = figure('Colormap',...
    [0.3 0 0;0.4 0 0;0.5 0 0;0.6 0 0;0.7 0 0;0.8 0 0;0.9 0 0]);


% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0649350649350649 0.11 0.805194805194805 0.815]);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create ylabel
ylabel('Torque (%)');

% Create xlabel
xlabel('Speed (%)','FontName','Times');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 700.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 600.5]);
box(axes1,'on');
axis(axes1,'ij');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times','FontSize',24,'Layer','top','XTick',...
    [1 70 140 210 280 350 420 490 560 630 700],'XTickLabel',...
    {'0','10','20','30','40','50','60','70','80','90','100'},'YTick',...
    [1 60 120 180 240 300 360 420 480 540 600],'YTickLabel',...
    {'100','90','80','70','60','50','40','30','20','10','0'});
% Create colorbar
cb = colorbar(axes1,'FontSize',24);
ylabel(cb, 'Efficiency (%)' , 'FontSize', 24 );

